# Workflow para construir y desplegar el backend en Google Cloud Run
# Guarda este archivo como .github/workflows/deploy-cloudrun.yml

name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gestor-de-contrasena-backend:latest ./backend

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gestor-de-contrasena-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gestor-de-contrasena-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gestor-de-contrasena-backend:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
